{% set name = "plotnine" %}
{% set version = "0.5.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "242a478db5b4b5e990ee10035e75e5b9a2a3850532141143bd68fd6efaf25c49" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - pip

  run:
    - python
    - six
    - mizani >=0.4.5
    - matplotlib >=2.1.0
    - numpy
    - scipy >=1.0.0
    - patsy >=0.4.1
    - statsmodels >=0.8.0
    - pandas >=0.21.0
    - geopandas >=0.3.0
    - descartes >=1.1.0

test:
  imports:
    - plotnine
    - plotnine.coords
    - plotnine.data
    - plotnine.facets
    - plotnine.geoms
    - plotnine.guides
    - plotnine.positions
    - plotnine.scales
    - plotnine.stats
    - plotnine.tests
    - plotnine.themes

about:
  home: https://github.com/has2k1/plotnine
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: GPL 2.0
  license_family: GPL2
  summary: 'A grammar of graphics for python'
  dev_url: https://github.com/has2k1/plotnine
  doc_url: https://plotnine.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
