{% set name = "plotnine" %}
{% set version = "0.14.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "c24cc5a5c38caf0296faa59fc5bf2a131bce0872991021eb1740a7567b93774a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.10.0
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python >=3.10.0
    - matplotlib-base >=3.8.0
    - pandas >=2.2.0
    - mizani >=0.13.0,<0.14.0
    - numpy >=1.23.5
    - scipy >=1.8.0
    - statsmodels >=0.14.0
    # - geopandas >=0.3.0

test:
  requires:
    - pip
    - pytest
    - pytest-cov
  imports:
    - plotnine
    - plotnine.coords
    - plotnine.data
    - plotnine.facets
    - plotnine.geoms
    - plotnine.guides
    - plotnine.mapping
    - plotnine.positions
    - plotnine.scales
    - plotnine.stats
    - plotnine.themes
  source_files:
    - tests
    - pyproject.toml
  commands:
    # The pip version can reported incorrectly if setuptools_scm isn't available
    # at build time
    - pip list | grep -i {{ name }} | grep {{ version }}
    - pip check
    - echo $PWD
    - ls -larth
    # - pytest

about:
  home: https://github.com/has2k1/plotnine
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: MIT
  summary: A grammar of graphics for python
  dev_url: https://github.com/has2k1/plotnine
  doc_url: https://plotnine.org

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
