{% set name = "plotnine" %}
{% set version = "0.7.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "8ee67cbf010ccea32670760e930b7b02177030a89ccdf85e35d156a96ce36cd3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  build:
    - python >=3.6.0
    - pip

  run:
    - python >=3.6.0
    - mizani >=0.7.1
    - matplotlib-base >=3.1.1
    - numpy >=1.16.0
    - scipy >=1.2.0
    - patsy >=0.5.1
    - statsmodels >=0.11.1
    - pandas >=1.0.3
    # - geopandas >=0.3.0
    - descartes >=1.1.0

test:
  imports:
    - plotnine
    - plotnine.coords
    - plotnine.data
    - plotnine.facets
    - plotnine.geoms
    - plotnine.guides
    - plotnine.positions
    - plotnine.scales
    - plotnine.stats
    - plotnine.tests
    - plotnine.themes

about:
  home: https://github.com/has2k1/plotnine
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: GPL 2.0
  license_family: GPL2
  summary: A grammar of graphics for python
  dev_url: https://github.com/has2k1/plotnine
  doc_url: https://plotnine.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
