{% set name = "plotnine" %}
{% set version = "0.12.1" %}
{% set bundle = "tar.gz" %}
{% set hash = "be852c6e50e331ad250151dc4120f269ee9ae5e795f67030f7794718b502592a" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.8.0
    - pip
    - setuptools
    - setuptools_scm

  run:
    - python >=3.8.0
    - mizani >=0.8.1
    - matplotlib-base >=3.5.0
    - numpy >=1.19.0
    - scipy >=1.5.0
    - patsy >=0.5.1
    - statsmodels >=0.13.2
    - pandas >=1.3.5
    # - geopandas >=0.3.0

test:
  requires:
    - pip
    - pytest
    - pytest-cov
    - geopandas
  imports:
    - plotnine
    - plotnine.coords
    - plotnine.data
    - plotnine.facets
    - plotnine.geoms
    - plotnine.guides
    - plotnine.mapping
    - plotnine.positions
    - plotnine.scales
    - plotnine.stats
    - plotnine.themes
  source_files:
    - tests
    - pyproject.toml
  commands:
    # The pip version can reported incorrectly if setuptools_scm isn't available
    # at build time
    - pip list | grep -i {{ name }} | grep {{ version }}
    - pip check
    - echo $PWD
    - ls -larth
    # - pytest

about:
  home: https://github.com/has2k1/plotnine
  license_file: {{ RECIPE_DIR }}/LICENSE
  license: MIT
  summary: A grammar of graphics for python
  dev_url: https://github.com/has2k1/plotnine
  doc_url: https://plotnine.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - has2k1
